### ISSUE TITLE
Error connecting to postgres when using the docker-compose

### ISSUE THREAD

**Issue by weebl2000** [pi0neerpat/indexer-docker-compose#13]
Trying to run the graph-node yields an error connecting to postgres:

```
graph-node-indexer_1  | Feb 01 15:58:43.065 INFO Creating transport, capabilities: archive, trace, url: http://172.17.0.1:8545, network: mainnet
graph-node-indexer_1  | thread '<unnamed>' panicked at 'failed to connect notification listener to Postgres: Error(ConnectParams("Invalid \':\' in authority."))', store/postgres/src/notification_listener.rs:122:22

```

Anyone else experience this?

**Comment by nivida** [comment]
Hey! After updating our local dev env did we encounter the same problem. In the end, were we just forced to remove the anyways default port of Postgres in our docker-compose file. :-)

**Comment by pi0neerpat** [comment]
Thanks for posting @nivida , would you mind sharing how your docker-compose looks now?

**Comment by rsolari** [comment]
I also had this issue when I upgraded to the latest graph node @pi0neerpat:

My new  docker-compose:
```
  graphnode-indexer:
    image: graphprotocol/graph-node:latest
    environment:
      postgres_host: '${DB_HOST}'
      postgres_port: 5432
```

The old docker-compose had the port in the host, like this:
```
  graphnode-indexer:
    image: graphprotocol/graph-node:latest
    environment:
      postgres_host: '${DB_HOST}:5432'
```
